### ISSUE TITLE
不支持koa？

### ISSUE THREAD

**Issue by xsbchen** [ali-sdk/node-profiler#10]
``` javascript
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:445:25)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
```

**Comment by JacksonTian** [comment]
加 `--harmony`
