### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by whitekyo** [ali-sdk/node-profiler#20]
CXX(target) Release/obj.target/heapdump/src/heapdump.o
In file included from ../src/heapdump.cc:18:
../src/util.h:16:29: error: expected ';' after expression
      v8::String::AsciiValue string(value);
                            ^
                            ;
../src/util.h:16:19: error: no member named 'AsciiValue' in 'v8::String'
      v8::String::AsciiValue string(value);
      ~~~~~~~~~~~~^
../src/util.h:16:30: error: use of undeclared identifier 'string'
      v8::String::AsciiValue string(value);
                             ^
../src/util.h:17:35: error: use of undeclared identifier 'string'
      char *str = (char *) malloc(string.length() + 1);
                                  ^
../src/util.h:18:20: error: use of undeclared identifier 'string'
      strcpy(str, *string);

**Comment by whitekyo** [comment]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yangcheng/node_modules/node-profiler
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by whitekyo** [comment]
我使用npm install node-profiler进行安装
