### ISSUE TITLE
项目中有 C/C++ Addons 的 package 是不是就不能用了？

### ISSUE THREAD

**Issue by jkeylu** [ali-sdk/node-profiler#5]
```
Error: %1 is not a valid Win32 application.
C:\Users\jKey\www\node_modules\bcrypt\build\Release\bcrypt_lib.node
    at Error (native)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (C:\Users\jKey\www\node_modules\pmx\lib\transacti
on.js:62:21)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
    at bindings (C:\Users\jKey\www\node_modules\bcrypt\node_modules\bindings\
bindings.js:76:44)
    at Object.<anonymous> (C:\Users\jKey\www\node_modules\bcrypt\bcrypt.js:3:
35)
    at Module._compile (module.js:462:26)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (C:\Users\jKey\www\node_modules\pmx\lib\transacti
on.js:62:21)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
    at Object.<anonymous> (C:\Users\jKey\www\server\modules\core\user-provide
r.ts:1:34)
```

**Comment by JacksonTian** [comment]
Node Profiler的版本和Node的版本一一对应。只要你的代码能在node v0.12.6下运行，就可以用node-profiler。

**Comment by yjhjstz** [comment]
你是win32平台？＠jkeylu

**Comment by jkeylu** [comment]
之前是在 win64 下用的 node v0.10.6 32bit 版本，
后来升级 node 到 node v0.12.6 64bit 版本，还是不行，就放弃折腾了
今天在 mac 上试了下没问题

**Comment by JacksonTian** [comment]
仅支持64位
